Revert "fix Exception in thread "main" java.lang.NoSuchMethodError: org.sprin… (#135)"
This reverts commit c630de85e9252509347e77d86c631c1eeed3ba1b.